### ISSUE TITLE
Put Hosted-Web-App back in main repo release/master branch?

### ISSUE THREAD

**Issue by cdcv** [Microsoft/cordova-samples#85]
It appears that hosted-web-app has been removed from the main repo.
I see that there is a new branch called hosted-app-2017.
The world needs the ability to make hosted web apps simply.
See for instance:
https://stackoverflow.com/questions/48476685/how-to-make-a-simple-cordova-hosted-webapp-that-retrieves-content-from-a-remote
It would be great if you could add this branch back into the main repo (first) and add some documentation to it (second) so that the rest of us can use it.
Meanwhile, going to attempt to use the hosted-app-2017 branch, but not sure what state it's in.
Thanks for your help in creating this repo.

Thanks

**Comment by StarfoxMulder** [comment]
Agreed.  I'm trying to follow [Microsoft's Run Your Hosted Web App in an Apache Cordova App guide](https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/tips-workarounds/run-web-app-in-cordovahttps://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/tips-workarounds/run-web-app-in-cordova) which links to and is intended to be used with this repo, but without the hosted-web-app folder the content doesn't match up.  

Did I stumble upon some outdated documentation or is this mismatch a legitimate issue?

Thanks!

**Comment by jwargo** [comment]
I worked on the docs as a contractor to Microsoft more than a year ago. I've not touched them since.  If I remember correctly, I updated the source code as I updated the doc, but I no longer have those files. All I can suggest is that you look back in history to find it.

**Comment by jwargo** [comment]
I just submitted a PR to put those files back in to the repo and asked one of my colleagues to look at it.

**Comment by StarfoxMulder** [comment]
Hell yeah!! Thanks @jwargo -- very much appreciate your work on the docs and being so proactive about helping us out here!!

**Comment by jmatthiesen** [comment]
This is merged back into master, now. Thanks all!
