### ISSUE TITLE
Password in sample...

### ISSUE THREAD

**Issue by JohnMcLear** [Microsoft/cordova-samples#87]
https://github.com/Microsoft/cordova-samples/blob/f5cb284837f35664165f814990b215dd0d03fb69/ui-testing/test08.js#L45

**Comment by jmatthiesen** [comment]
Thanks for this! I removed the password and the account should be deactivated for anyone that later finds this password in history. :)

**Comment by JohnMcLear** [comment]
Np


________________________________
